apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
#  generateName: python-script-
  name: dg-dev
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: harbor-cicd.taco-cat.xyz/dev/dev-donggyu:v0.1.0
        imagePullPolicy: Always
        command: ["python", "/app/app.py"]
